on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
#    - uses: actions/checkout@master      
#    - name: npm install, build, and test
#      run: |
#        npm install
#        npm run build --if-present
#        npm run test --if-present
#        echo "all good"

#    - uses: actions/aws/cli@master
#    - name: use of vars   
#      env:
#        MY_VAR: Hi there! My name is
#        FIRST_NAME: Mona
#        MIDDLE_NAME: The
#        LAST_NAME: Octocat
#      run: |
#        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    
#    - uses: actions/aws/cli@master  
#    - run: aws s3 ls
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name:  describe apps
      uses: actions/aws/cli@master  
      with: 
        args: "elasticbeanstalk describe-applications"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  
 
    #- name: 'AWS CLI'
    #  uses = "actions/aws/cli@master"
    #  args = 
    #  secrets = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]


