on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
#    - uses: actions/checkout@master      
    
#    - uses: actions/aws/cli@master  
#    - run: aws s3 ls
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#    - uses: actions/checkout@master
    - uses: actions/aws/cli@master 
      with:
         args: elasticbeanstalk delete-application --application-name rai-demo2
#        args: elasticbeanstalk create-application-version --application-name rai-demo --version-label v0.3 --description MyAppv1 --source-bundle S3Bucket="rai-demo-bucket",S3Key="NodeExpressSampleApp.1.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



#        args: elasticbeanstalk create-application-version --application-name raiDemoApp --version-label v0.0.2 --source-bundle S3Bucket="elasticbeanstalk-us-east-2-867889859992",S3Key="myapp.zip"
#        args: s3 cp myapp.zip s3://elasticbeanstalk-us-east-2-867889859992/     
#        args: elasticbeanstalk update-environment --application-name raiDemoApp --environment-name Raidemoapp-env --version-label v0.2